name: Run packer build on a template file

on:
  push:
    branches:
        - 'master'
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Packer build
        uses: riznob/packer-build-action@v1.1
        with:
          templateFile: 'ubuntu.ami.json'
          workingDir: '.'
        env:
          aws_access_key: ${{ secrets.AWS_AMI_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_AMI_SECRET_KEY }}
